[package]
name = "fenix"
version = "0.1.0"
edition = "2021"
authors = ["Small San", "DefinitelyNotSmallSan@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fenix"
crate-type = ["lib"]

[[test]]
name = "fen_test"
path = "tests/fen_test.rs"

[dependencies]


